package com.destiny.gamegerbanglogika.Model.Dificulty.Medium;

import com.destiny.gamegerbanglogika.Model.DataModel;
import com.destiny.gamegerbanglogika.R;

import java.util.ArrayList;

public class NormalModel
{
    public static String[][] data = new String[][]{
            //OR
            {"1",
                    String.valueOf(R.drawable.normal_1_2_or_mati),
                    String.valueOf(R.drawable.normal_1_2_or_nyala),
                    "XOR",
                    "XNOR",
                    "NAND",
                    "XNOR",
                    String.valueOf(R.drawable.or_n_1)
            },
            {"2",
                    String.valueOf(R.drawable.normal_1_2_or_mati),
                    String.valueOf(R.drawable.normal_1_2_or_nyala),
                    "AND",
                    "XOR",
                    "NAND",
                    "AND",
                    String.valueOf(R.drawable.or_n_2)
            },
            {"3",
                    String.valueOf(R.drawable.normal_3_or_mati),
                    String.valueOf(R.drawable.normal_3_or_nyala),
                    "NAND",
                    "NOR",
                    "AND",
                    "AND",
                    String.valueOf(R.drawable.or_n_3)
            },
            {"4",
                    String.valueOf(R.drawable.normal_4_or_mati),
                    String.valueOf(R.drawable.normal_4_or_nyala),
                    "NAND",
                    "NOR",
                    "AND",
                    "NAND",
                    String.valueOf(R.drawable.or_n_4)


            },
            {"5",
                    String.valueOf(R.drawable.normal_5_or_mati),
                    String.valueOf(R.drawable.normal_5_or_nyala),
                    "XNOR",
                    "AND",
                    "OR",
                    "OR",
                    String.valueOf(R.drawable.or_n_5)
            },
            {"6",
                    String.valueOf(R.drawable.normal_6_or_mati),
                    String.valueOf(R.drawable.normal_6_or_nyala),
                    "XNOR",
                    "AND",
                    "OR",
                    "XNOR",
                    String.valueOf(R.drawable.or_n_6)
            },
            //AND
            {"7",
                    String.valueOf(R.drawable.normal_1_and_mati),
                    String.valueOf(R.drawable.normal_1_and_nyala),
                    "NAND",
                    "XNOR",
                    "AND",
                    "NAND",
                    String.valueOf(R.drawable.and_n_1)
            },
            {"8",
                    String.valueOf(R.drawable.normal_2_and_mati),
                    String.valueOf(R.drawable.normal_2_and_nyala),
                    "NAND",
                    "XNOR",
                    "AND",
                    "NAND",
                    String.valueOf(R.drawable.and_n_2)
            },
            {"9",
                    String.valueOf(R.drawable.normal_3_and_mati),
                    String.valueOf(R.drawable.normal_3_and_nyala),
                    "XNOR",
                    "NOR",
                    "OR",
                    "OR",
                    String.valueOf(R.drawable.and_n_3)
            },
            {"10",
                    String.valueOf(R.drawable.normal_4_and_mati),
                    String.valueOf(R.drawable.normal_4_and_nyala),
                    "XNOR",
                    "XOR",
                    "OR",
                    "XNOR",
                    String.valueOf(R.drawable.and_n_4)
            },
            {"11",
                    String.valueOf(R.drawable.normal_5_and_mati),
                    String.valueOf(R.drawable.normal_5_and_nyala),
                    "NOR",
                    "XOR",
                    "OR",
                    "NOR",
                    String.valueOf(R.drawable.and_n_5)
            },
            {"12",
                    String.valueOf(R.drawable.normal_6_and_mati),
                    String.valueOf(R.drawable.normal_6_and_nyala),
                    "XOR",
                    "NAND",
                    "OR",
                    "NAND",
                    String.valueOf(R.drawable.and_n_6)
            },
            //NAND
            {"13",
                    String.valueOf(R.drawable.normal_1_2_nand_mati),
                    String.valueOf(R.drawable.normal_1_2_nand_nyala),
                    "NAND",
                    "OR",
                    "XOR",
                    "OR",
                    String.valueOf(R.drawable.nand_n_1)
            },
            {"14",
                    String.valueOf(R.drawable.normal_1_2_nand_mati),
                    String.valueOf(R.drawable.normal_1_2_nand_nyala),
                    "XOR",
                    "NOR",
                    "AND",
                    "AND",
                    String.valueOf(R.drawable.nand_n_2)
            },
            {"15",
                    String.valueOf(R.drawable.normal_3_nand_mati),
                    String.valueOf(R.drawable.normal_3_nand_nyala),
                    "XOR",
                    "NAND",
                    "OR",
                    "OR",
                    String.valueOf(R.drawable.nand_n_3)
            },
            {"16",
                    String.valueOf(R.drawable.normal_4_nand_mati),
                    String.valueOf(R.drawable.normal_4_nand_nyala),
                    "XOR",
                    "NOR",
                    "XNOR",
                    "XOR",
                    String.valueOf(R.drawable.nand_n_4)
            },
            {"17",
                    String.valueOf(R.drawable.normal_5_6_nand_mati),
                    String.valueOf(R.drawable.normal_5_6_nand_nyala),
                    "XOR",
                    "NOR",
                    "XNOR",
                    "XNOR",
                    String.valueOf(R.drawable.nand_n_5)
            },
            {"18",
                    String.valueOf(R.drawable.normal_5_6_nand_mati),
                    String.valueOf(R.drawable.normal_5_6_nand_nyala),
                    "XOR",
                    "AND",
                    "NAND",
                    "AND",
                    String.valueOf(R.drawable.nand_n_6)
            },
            //NOR
            {"19",
                    String.valueOf(R.drawable.normal_1_2_nor_mati),
                    String.valueOf(R.drawable.normal_1_2_nor_nyala),
                    "XOR",
                    "AND",
                    "NAND",
                    "AND",
                    String.valueOf(R.drawable.nor_n_1)
            },
            {"20",
                    String.valueOf(R.drawable.normal_1_2_nor_mati),
                    String.valueOf(R.drawable.normal_1_2_nor_nyala),
                    "NAND",
                    "OR",
                    "XNOR",
                    "XNOR",
                    String.valueOf(R.drawable.nor_n_2)
            },
            {"21",
                    String.valueOf(R.drawable.normal_3_nor_mati),
                    String.valueOf(R.drawable.normal_3_nor_nyala),
                    "NOR",
                    "XOR",
                    "OR",
                    "NOR",
                    String.valueOf(R.drawable.nor_n_3)
            },
            {"22",
                    String.valueOf(R.drawable.normal_4_nor_mati),
                    String.valueOf(R.drawable.normal_4_nor_nyala),
                    "NAND",
                    "OR",
                    "XOR",
                    "NAND",
                    String.valueOf(R.drawable.nor_n_4)
            },
            {"23",
                    String.valueOf(R.drawable.normal_5_nor_mati),
                    String.valueOf(R.drawable.normal_5_nor_nyala),
                    "NOR",
                    "XNOR",
                    "OR",
                    "OR",
                    String.valueOf(R.drawable.nor_n_5)
            },
            {"24",
                    String.valueOf(R.drawable.normal_6_nor_mati),
                    String.valueOf(R.drawable.normal_6_nor_nyala),
                    "NOR",
                    "XNOR",
                    "OR",
                    "OR",
                    String.valueOf(R.drawable.nor_n_6)
            },
            //XOR
            {"25",
                    String.valueOf(R.drawable.normal_1_2_xor_mati),
                    String.valueOf(R.drawable.normal_1_2_xor_nyala),
                    "XOR",
                    "XNOR",
                    "NOR",
                    "XNOR",
                    String.valueOf(R.drawable.xor_n_1)
            },
            {"26",
                    String.valueOf(R.drawable.normal_1_2_xor_mati),
                    String.valueOf(R.drawable.normal_1_2_xor_nyala),
                    "NOR",
                    "NAND",
                    "OR",
                    "OR",
                    String.valueOf(R.drawable.xor_n_2)
            },
            {"27",
                    String.valueOf(R.drawable.normal_3_xor_mati),
                    String.valueOf(R.drawable.normal_3_xor_nyala),
                    "NOR",
                    "NAND",
                    "OR",
                    "OR",
                    String.valueOf(R.drawable.xor_n_3)
            },
            {"28",
                    String.valueOf(R.drawable.normal_4_xor_mati),
                    String.valueOf(R.drawable.normal_4_xor_nyala),
                    "NAND",
                    "XNOR",
                    "NOR",
                    "NAND",
                    String.valueOf(R.drawable.xor_n_4)
            },
            {"29",
                    String.valueOf(R.drawable.normal_5_xor_mati),
                    String.valueOf(R.drawable.normal_5_xor_nyala),
                    "XNOR",
                    "AND",
                    "OR",
                    "OR",
                    String.valueOf(R.drawable.xor_n_5)
            },
            {"30",
                    String.valueOf(R.drawable.normal_6_xor_mati),
                    String.valueOf(R.drawable.normal_6_xor_nyala),
                    "AND",
                    "NOR",
                    "XOR",
                    "AND",
                    String.valueOf(R.drawable.xor_n_6)
            },
            //XNOR
            {"31",
                    String.valueOf(R.drawable.normal_1_xnor_mati),
                    String.valueOf(R.drawable.normal_1_xnor_nyala),
                    "NOR",
                    "XNOR",
                    "XOR",
                    "XNOR",
                    String.valueOf(R.drawable.xnor_n_1)
            },
            {"32",
                    String.valueOf(R.drawable.normal_2_3_xnor_mati),
                    String.valueOf(R.drawable.normal_2_3_xnor_nyala),
                    "NOR",
                    "AND",
                    "OR",
                    "NOR",
                    String.valueOf(R.drawable.xnor_n_2)
            },
            {"33",
                    String.valueOf(R.drawable.normal_2_3_xnor_mati),
                    String.valueOf(R.drawable.normal_2_3_xnor_nyala),
                    "OR",
                    "AND",
                    "XOR",
                    "XOR",
                    String.valueOf(R.drawable.xnor_n_3)
            },
            {"34",
                    String.valueOf(R.drawable.normal_4_xnor_mati),
                    String.valueOf(R.drawable.normal_4_xnor_nyala),
                    "NOR",
                    "AND",
                    "XOR",
                    "XOR",
                    String.valueOf(R.drawable.xnor_n_4)
            },
            {"35",
                    String.valueOf(R.drawable.normal_5_xnor_mati),
                    String.valueOf(R.drawable.normal_5_xnor_nyala),
                    "OR",
                    "XNOR",
                    "NAND",
                    "NAND",
                    String.valueOf(R.drawable.xnor_n_5)
            },
            {"36",
                    String.valueOf(R.drawable.normal_6_xnor_mati),
                    String.valueOf(R.drawable.normal_6_xnor_nyala),
                    "NAND",
                    "XNOR",
                    "OR",
                    "OR",
                    String.valueOf(R.drawable.xnor_n_6)
            },
    };
    public static ArrayList<DataModel> getListData(){
        DataModel models = null;
        ArrayList<DataModel> list = new ArrayList<>();
        for (String[] aData : data) {
            models = new DataModel();
            models.setNo(aData[0]);
            models.setGambar(aData[1]);
            models.setGambar2(aData[2]);
            models.setJawaban1(aData[3]);
            models.setJawaban2(aData[4]);
            models.setJawaban3(aData[5]);
            models.setJawaban(aData[6]);
            models.setTable(aData[7]);
            list.add(models);
        }
        return list;
    }
}
